config/routes.rb
Rails.application.routes.draw do

	root to: 'welcome#index'
  get 'welcome/index', to: 'welcome#index'

	get 'users/signup', to: 'auth#signupView'
	post 'users/signup', to: 'auth#signup'
	get 'users/login', to: 'auth#loginView'
	post 'users/login', to: 'auth#login'
	post 'users/logout', to: 'auth#logout'
	get 'users/index', to: 'users#index'
	get 'users', to: 'users#index'


  get '/searches', to: 'searches#searchView'
  post '/searches', to: 'searches#search'

	# error pages
	%w( 404 422 500 503 ).each do |code|
		get code, :to => "errors#show", :code => code
	end

	get '*path', to: "errors#show"

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/search.rb
class Search < ApplicationRecord
	validates :word, presence: { message: "A search word is required" }
	validates :start_url, presence: { message: "A start url is required" }
	
	belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
	has_secure_password
	validates :name, presence: { message: "Name is required" }, length: { in: 5..50, message: "Name length must not outlimit [5-50] characters" }, format: { with: /\A[A-Za-z][A-Za-z\'\-]+([\ A-Za-z][A-Za-z\'\-]+)*/, message: "Invalid name. You can only use alphabets, numbers, . and _" }
	validates :username, presence: { message: "Username is required" }, uniqueness: {message: "Username already used."}, length: { in: 5..50, message: "Username length must not outlimit [5-50] characters" }, format: { with: /\A(?=.{5,50}$)(?![_.])(?!.*[_.]{2})[a-zA-Z0-9._]+(?<![_.])\z/, message: "Invalid username. You can only use alphabets, numbers, . and _" }
	# 	/\A(?=.{5,50}$)(?![_.])(?!.*[_.]{2})[a-zA-Z0-9._]+(?<![_.])\z/
	#    └─────┬────┘└───┬──┘└─────┬─────┘└─────┬─────┘ └───┬───┘
	#          │         │         │            │           no _ or . at the end
	#          │         │         │            │
	#          │         │         │            allowed characters
	#          │         │         │
	#          │         │         no __ or _. or ._ or .. inside
	#          │         │
	#          │         no _ or . at the beginning
	#          │
	#          username is 5-20 characters long
  validates :password, presence: true, length: { in: 8..50 }

	has_many :searches
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

	before_action :authorized

	helper_method :current_user
	helper_method :logged_in?

	def current_user   
		# if session[:user_id]
    #   @c_user = User.find(session[:user_id]) # current user
    # end

		# instead of getting the user everytime from the db, you get it from the session store (redis)
		return session[:user]
	end

	def logged_in?     
    !current_user.nil?
	end

	def authorized
		redirect_to welcome_index_path unless logged_in?
	end

end

app/controllers/auth_controller.rb
class AuthController < ApplicationController

	skip_before_action :authorized

	def signupView
		if(logged_in?) 
      redirect_to users_index_path
		else
			@user ||= User.new
		end
  end

  def signup
		user_params = params.require(:user).permit(:name, :username, :password, :password_confirmation)
		@user = User.create(user_params)
    if @user.valid?
      @user.save
      # session[:user_id] = @user.id
			session[:user] = @user
      redirect_to users_index_path
    else  
			render 'signupView'
    end
  end


  def loginView
		if(logged_in?) 
      redirect_to users_index_path
		else
			@user ||= User.new
		end
  end

	def login
		user_params = params.require(:user).permit(:username, :password)
		@user = User.find_by(username: user_params[:username])
    if @user && @user.authenticate(user_params[:password])
      # session[:user_id] = @user.id
			session[:user] = @user
      redirect_to users_index_path
    else  
			render 'loginView'
    end
  end

	def logout
			# session[:user_id] = nil
			@session = nil
			session[:user] = nil
			redirect_to welcome_index_path
	end

end

app/controllers/errors_controller.rb
class ErrorsController < ApplicationController
  def show
		status_code = params[:code] || 500
    flash.alert = "Status #{status_code}"
    # render status_code.to_s, status: status_code
  end
end

app/controllers/searches_controller.rb
require 'uri'
require 'net/http'
# require 'pp'

class SearchesController < ApplicationController


  def searchView
		@search ||= Search.new
  end

  def search
		# get search parameters
		search_params = params.require(:search).permit(:word, :start_url, :max_urls_count)
		#insert search to users db
		new_search = params.require(:search).permit(:word, :start_url)
		new_search["user_id"] = current_user["id"]
		@search = Search.create(new_search)
		if @search.valid?
      @search.save
    else  
			render 'searchView'
			return
    end

		# define instance vairiable for the result search index which will be populated and passed to the view.
		@total_index = Hash.new
		# initialize crawler urls array
		@crawler_urls = [search_params[:start_url]]
		# call crawler
		crawler 0, @crawler_urls, search_params[:max_urls_count].to_i
		# call mapper_reducer func
		mapper_reducer @crawler_urls, search_params[:max_urls_count].to_i
		# pass result to view
		@searched_word = search_params[:word]
		
		render 'searchView'

  end

	def mapper_reducer crawler_urls, max_urls_count
		idx = 0
		while idx < max_urls_count do

			# Mapper
			threads = []
			5.times do |i|
				if idx < max_urls_count
					threads << Thread.new(idx) { |arg_idx| Thread.current[:index] = indexer crawler_urls[arg_idx]; Thread.current[:url] = crawler_urls[arg_idx];}
					idx += 1
				else
					break
				end
			end

			# Reducer
			threads.each do |t|
				t.join
		 		reducer t[:index], t[:url]
			end

			# clear threads array
			threads.clear

		end
	end

	def reducer index, url
		index.each do |word, word_count|
			if(@total_index[word].nil?)
				@total_index[word] = [{:count => word_count, :document => url}]
			else
				@total_index[word] << {:count => word_count, :document => url}
			end
		end
	end

	def indexer url
		page = getPage url
		page.downcase!
		words = getWords page
		index = Hash.new(0)
		words.each {|word| index[word] += 1 if word.length > 0}
		return index
	end

	def getPage arg_url
		uri = URI(arg_url)
		res = Net::HTTP.get_response(uri)
		return res.body
	end

	def getWords text
		return	text.split(/\W+/)
	end

	def crawler idx, urls_arr, max_urls_count
		body = getPage urls_arr[idx]
		idx += 1
		search_urls = URI.extract(body).grep(/^https?:/)
		if(search_urls.length == 0) 
			return
		end
		diff = max_urls_count - urls_arr.length
		if(search_urls.length >= diff)
			urls_arr.concat search_urls[0, diff] if diff > 0
		else
			urls_arr.concat search_urls # append the whole array
			crawler idx, urls_arr, max_urls_count
		end
	end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
		@searches = Search.where(:user_id => current_user["id"])
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
	skip_before_action :authorized
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/auth_helper.rb
module AuthHelper
end

app/helpers/errors_helper.rb
module ErrorsHelper
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SimpleSearchEngine</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

		<!-- Bootstrap -->
		<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
		<%= favicon_link_tag asset_path('search.ico') %>
  </head>

  <body>
    <%= yield %>

		<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
		<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
		<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
  </body>
</html>

app/views/searches/searchView.html.erb
<button class="btn btn-lg btn-primary"><%= link_to "Profile", '/users/index', class: "text-white text-decoration-none"%></button>
<div class="container">
	<h1>Search</h1>
	<div class="pa-2">
	<%= form_with model: @search, url: searches_path(@search) do |f| %>
		<div class="form-group">
			<%= f.label :word%>
			<%= f.text_field :word,  class: 'form-control' %>
		</div>
		<div class="form-group">
			<%= f.label :start_url%>
			<%= f.text_field :start_url, class: 'form-control' %>
		</div>
		<div class="form-group">
			<%= f.label :maximum_number_of_urls_for_crawling%>
			<%= f.text_field :max_urls_count, class: 'form-control' %>
		</div>
		<div class="form-group">
			<%= f.submit "Search", class: "btn btn-primary" %>
		</div>
	<%end%>
	</div>

	<% if @search.errors.any? %>
		<div id="error_explanation" style="color: red;">
			<h2><%= pluralize(@search.errors.count, "error") %> occured in your input:</h2>
			<ul style="list-style-type: none;">
				<% @search.errors.each do |error| %>
					<li>-- <%= error.message %></li>
				<% end %>
			</ul>
		</div>
	<% end %>

	<% if !@total_index.nil? &&  %>
		<div class="container">
			<h2>Documents that have the word: <b>"<%=@searched_word%>"</b><br></h2>
				<% @total_index[@searched_word.downcase].each do |doc| %>
				<ul class="list-group">
					<li class="list-group-item">Document URL: <a href="<%=doc[:document] %>"><%=doc[:document] %></a></li>
					<li class="list-group-item">Word occurrence count in the document: <%=doc[:count]%></li>
				</ul>
				<% end %>	
				<!-- <p><%= @total_index[@searched_word.downcase] %></p> -->
		</div>

		<div class="container py-4">
			<h2>The Crawled Urls</h2>
			<ul class="list-group" style="list-style-type: none">
				<% @crawler_urls.each do |url| %>
					<li>-- <a href="<%=url%>"><%=url%></a></li>
				<% end %>
			</ul>
		</div>
		
		<div class="container py-4">
			<h2>The Complete Index</h2>
			<!-- <%= debug @total_index %> -->
			<ul class="list-group">
				<% @total_index.each do |word, docs_array| %>
					<li class="list-group-item">					
						<h4><b><%=word%>:</b></h4>
						<% @total_index[word].each do |doc| %>
						<div class="py-2">
							<ul class="list-group">
								<li class="list-group-item">Document URL: <a href="<%=doc[:document] %>"><%=doc[:document] %></a></li>
								<li class="list-group-item">Word occurrence count: <%=doc[:count]%></li>
							</ul>
						</div>
						<% end %>	
					</li>
				<% end %> 
			</ul>
		</div>

	<%else%>
		<p>No words found!</p>
	<% end %>


</div>

app/views/users/index.html.erb
<%= button_to "Logout", '/users/logout', method: :post, class: "btn btn-primary"%>
<div class="container">
	<h1  class="text-center">Profile</h1>
	<p class="text-center">Welcome, <%= current_user["name"] %>!</p>

		<div class="container mt-5 ma-2">
			<div class="row my-2">
				<h2 class="col-10">You searched for: </h2>
				<div class="col-2">
					<button class="btn btn-primary"><%= link_to "Search", '/searches', class: "text-white text-decoration-none"%></button>
				</div>
			</div>
			<div class="card container pa-2">
					<% if @searches.any? %>
						<% @searches.each do |search| %>
							<ul class="list-group my-2">
								<li class="list-group-item">Word: <%= search.word %></li>
								<li class="list-group-item">Starting from: <%= search.start_url %></li>
							</ul>
						<%end%>
					<%end%>
			</div>
		</div>
</div>

app/views/welcome/index.html.erb
<%= button_to "Logout", '/users/logout', method: :post, class: "btn btn-primary"%>
<div class="container">
	<h1 class="text-center">Welcome</h1>
	<% if logged_in? %>    
	<h1 class="text-center">Welcome, <%= current_user["name"] %>!</h1>

	<% else %>
		<div class="card text-center mt-5">
		<ul class="list-group">
			<li class="list-group-item"><button class="btn btn-lg btn-primary"><%= link_to "Login", '/users/login', class: "text-white text-decoration-none"%></button></li>
			<li class="list-group-item"><button class="btn btn-lg btn-primary"><%= link_to "Signup", '/users/signup', class: "text-white text-decoration-none"%></button></li>
		</ul>
		</div>
	<%end%>
</div>